export const TEMP_BOARD_TITLE = 'temporaire'
export const TEMP_BOARD_COLOR = '000000'
export const STACK_TODO_TITLE = 'A faire'
export const SECRETARIAT_LABEL_TITLE = 'secrétariat'
export const ACCOUNTING_LABEL_TITLE = 'comptabilité'
